on:
  push:
    branches: [ main ]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: emulation-as-a-service/cwl-action@main
        with:
          workflowPath: wrapped_workflow_example_workflow.cwl
          jobFilePath: workflow-test.yml
