on:
  push:
    branches: [ main ]

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CWL Runner
        run: sudo apt-get update && sudo apt-get install cwltool -y
      - name: Execute CWL
        run: cwl-runner --no-read-only  --force-docker-pull wrapped_workflow_example_workflow.cwl workflow-test.yml

